version: "3.8"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    volumes:
      - postgres-storage:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    # if you are running as root then set it to 0, else find the right id with the id -u command
    user: "0"
    ports:
      - "3000:3000"
    volumes:
      - "grafana_storage:/var/lib/grafana"
volumes:
  postgres-storage:
  grafana_storage: